name: Scan an image and attest the result
description: |
  This action scans an image using either trivy or grype,
  then attests the result using cosign.
inputs:
  image:
    description: OCI image
    required: true
  scanner:
    type: choice
    description: Which scanner to use, ("trivy" or "grype")
    options: [grype, trivy]
    required: true
  invocation-builder-id:
    description: in-toto value for invocation builder.id
    default: ${{ github.workflow }}
    required: true
  invocation-event-id:
    description: in-toto value for invocation event_id
    default: ${{ github.run_id }}
    required: true
  invocation-uri:
    description: in-toto value for invocation event_id
    default: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    required: true
runs:
  using: docker
  image: docker://ghcr.io/chainguard-dev/rumble:latest
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
      set -o errexit
      set -o pipefail
      set -x
      cosign copy -f ${{ inputs.image }} ${{ inputs.image }}-copy || ( \
        rm -rf "${HOME}/.docker" && cosign copy -f ${{ inputs.image }} ${{ inputs.image }}-copy )
  # args:
  #   - -image=${{ inputs.image }}
  #   - -scanner=${{ inputs.scanner }}
  #   - -invocation-builder-id=${{ inputs.invocation-builder-id }}
  #   - -invocation-event-id=${{ inputs.invocation-event-id }}
  #   - -invocation-uri=${{ inputs.invocation-uri }}
  #   - -attest
