package:
  name: rumble
  version: 0.1.0
  description: Data collection for base image CVEs etc.
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
  # Note: rumble shells out to the following tools,
  # thus listed as depenedncies for this package
  dependencies:
    runtime:
      - grype
      - trivy
      - cosign

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - ca-certificates-bundle
      - busybox
      - go

pipeline:
  - name: Build Go application
    runs: |
      set -x
      CGO_ENABLED=0 go build -o "${{targets.destdir}}/usr/sbin/rumble" .
