package:
  name: rumble
  version: 0.1.0
  description: Data collection for base image CVEs etc.
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
  # Note: rumble shells out to the following tools,
  # thus listed as dependencies for this package
  dependencies:
    runtime:
      - grype
      - syft
      - trivy
      - cosign

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - ca-certificates-bundle
      - busybox
      - go

pipeline:
  - name: Build Go application
    runs: |
      set -x
      CGO_ENABLED=0 go build -o "${{targets.destdir}}/usr/sbin/rumble" .
  - name: Create dummy Docker config for Google Cloud
    runs: |
      set -x
      mkdir -p "${{targets.destdir}}/etc/rumble/docker-dummy"
      echo '{}' > "${{targets.destdir}}/etc/rumble/docker-dummy/config.json"
