on:
  push:
    branches:
      - main
  #schedule:
  #  - cron: '0 1 * * *'
env:
  REF: "ghcr.io/chainguard-dev/rumble:latest"
  GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
  GCLOUD_DATASET: ${{ secrets.GCLOUD_DATASET }}
  GCLOUD_TABLE: ${{ secrets.GCLOUD_TABLE }}
  GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
concurrency: chainguard-public-scan
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          repository: chainguard-images/images
          path: chainguard-public-images
      - id: monopod
        run: |
          set -x
          cd chainguard-public-images/monopod/
          go build -o /tmp/monopod monopod.go
      - id: generate-matrix
        run: |
          set -x
          cd chainguard-public-images/ 
          echo "matrix=$(/tmp/monopod matrix)" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    permissions:
      id-token: write
      packages: write
      contents: read
    steps:
      - name: Run rumble on image
        run: |
          set -x
          echo "${GOOGLE_APPLICATION_CREDENTIALS_BASE64}" | base64 -d > google-creds.json
          IMAGE="$(echo "${{ matrix.apkoBaseTag }}:${{ matrix.apkoTargetTag }}" | sed 's|^ghcr\.io/chainguard-images/|cgr.dev/chainguard/|')"
          echo "Scanning: ${IMAGE}"
          env > github.env
          echo "GOOGLE_APPLICATION_CREDENTIALS=/google-creds.json" >> github.env
          docker run --rm \
            -v "${PWD}/google-creds.json":/google-creds.json \
            --env-file github.env \
            "${REF}" \
            -image "${IMAGE}"
