name: rumble-presubmit
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Run Go tests
        run: |
          set -x
          go test -v ./...
      - name: Build image
        run: |
          set -x
          ./scripts/build.sh
      - name: Check if image runs
        run: |
          set -x
          docker run --rm rumble:dev-amd64 \
            --attest=false --bigquery=false
