name: rumble-image-publish
on:
  push:
    branches:
      - main
  #schedule:
  #  - cron: '30 12 * * *'
  workflow_dispatch: {}
env:
  REF: "ghcr.io/chainguard-dev/rumble:latest"
  REGISTRY_USERNAME: ${{ github.repository_owner }}
  REGISTRY_PASSWORD: ${{ github.token }}
  COSIGN_EXPERIMENTAL: "true"
  CHAINGUARD_GITHUB_EVENT_NAME: "schedule"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # needed for GitHub OIDC Token **not production ready**
    steps:
      - name: Checkout source code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Publish image
        run: |
          set -x
          ./scripts/publish.sh
      - name: Attestationception!
        run: |
          set -x
          export DOCKER_CONFIG="$(mktemp -d)"
          docker login ghcr.io -u "${REGISTRY_USERNAME}" -p "${REGISTRY_PASSWORD}"
          docker run --rm -v "${DOCKER_CONFIG}":/config \
            -e DOCKER_CONFIG=/config \
            "${REF}" \
            -image "${REF}" \
            -attest
